#ifndef RADARDATARECEIVER_GLOBAL_H
#define RADARDATARECEIVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RADARDATARECEIVER_LIBRARY)
#define RADARDATARECEIVER_EXPORT Q_DECL_EXPORT
#else
#define RADARDATARECEIVER_EXPORT Q_DECL_IMPORT
#endif

#endif // RADARDATARECEIVER_GLOBAL_H
